frequency: 20s
components:
  - component_slug: "prow"
    sub_component_slug: "deck"
    http_monitor:
      url: "https://prow.ci.openshift.org/"
      code: 200
      retry_after: 5s
  - component_slug: "mocked"
    sub_component_slug: "frontend"
    http_monitor:
      url: "http://localhost:8081/health"
      code: 200
      retry_after: 5s
  # - component_slug: "prow"
  #   sub_component_slug: "tide"
  #   prometheus_monitor:
  #     url: "https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091"
  #     query: "up{job=\"tide\"}"
