global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mock-monitored-component'
    static_configs:
      - targets: ['host.containers.internal:8081']
        labels:
          instance: 'mock-component'

