apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: component-monitor
  namespace: ship-status
  labels:
    app: component-monitor
spec:
  to:
    kind: Service
    name: component-monitor
  port:
    targetPort: 8080
